<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">

<head>

<meta charset="utf-8" />
<meta name="generator" content="quarto-1.4.551" />

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />


<title>Dilara's Analytics Lab – STOP COMPLAINING, IT SOLVES NOTHING.</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>

<!-- htmldependencies:E3FAD763 -->
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css" />
</head>

<body>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="/index.html">
    <span class="navbar-title">Dilara&#39;s Analytics Lab</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
  aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"
  onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="/index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="/about.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="/posts.html"> 
<span class="menu-text">My Posts</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-emu660-coursework" role="button" data-bs-toggle="dropdown" aria-expanded="false" >
 <span class="menu-text">EMU660 Coursework</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-emu660-coursework">    
        <li>
    <a class="dropdown-item" href="/assignments.html">
 <span class="dropdown-text">Assignments</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="/project.html">
 <span class="dropdown-text">Project</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools tools-wide">
    <a href="https://github.com/Dilara-pro"  title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
    <a href="https://www.linkedin.com/in/dilara-akkus/"  title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-linkedin"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div id="quarto-toc-target"></div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" ></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">STOP COMPLAINING, IT SOLVES NOTHING.</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#are-we-aware" id="toc-are-we-aware"><span style="color:darkgreen">1. Are we aware?</span> <img src="assets/images/trash.jpg" width="109" height="27" /></a></li>
  <li><a href="#data" id="toc-data"><span style="color:darkgreen">2. Data</span> <img src="assets/images/data_symbol.jpg" width="43" height="29" /></a>
  <ul>
  <li><a href="#data-source" id="toc-data-source"><span style="color:darkblue">2.1 Data Source</span> <img src="assets/images/database.jpg" width="71" height="29" /></a></li>
  <li><a href="#general-information-about-the-main-data" id="toc-general-information-about-the-main-data"><span style="color:darkblue">2.2 General Information About the Main Data</span> <img src="assets/images/info.jpg" width="26" height="23" /></a></li>
  <li><a href="#reason-of-choice" id="toc-reason-of-choice"><span style="color:darkblue">2.3 Reason of Choice</span> <img src="assets/images/reason.jpg" width="25" height="21" /></a></li>
  <li><a href="#preprocessing" id="toc-preprocessing"><span style="color:darkblue">2.4 Preprocessing</span> <img src="assets/images/preprocess.jpg" width="29" height="24" /></a></li>
  </ul></li>
  <li><a href="#analysis" id="toc-analysis"><span style="color:darkgreen">3. Analysis</span> <img src="assets/images/analysis.jpg" width="36" height="29" /></a>
  <ul>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis"><span style="color:darkblue">3.1 Exploratory Data Analysis</span> <img src="assets/images/EDA.jpg" width="23" height="21" /></a></li>
  <li><a href="#regression-analysis" id="toc-regression-analysis"><span style="color:darkblue">3.2 Regression Analysis</span> <img src="assets/images/tredn.jpg" width="26" height="23" /></a></li>
  <li><a href="#time-series-analysis" id="toc-time-series-analysis"><span style="color:darkblue">3.3 Time Series Analysis</span> <img src="assets/images/model.jpg" width="36" height="28" /></a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion"><span style="color:darkgreen">4. Conclusion</span> <img src="assets/images/discussion.png" class="img-fluid" width="27" /></a></li>
  <li><a href="#references" id="toc-references"><span style="color:darkgreen">References</span> <img src="assets/images/references.jpg" width="30" height="29" /></a></li>
  </ul>
</nav>
<p>My project will provide insights about <strong>waste management</strong>, which is of vital importance to the world and humanity. I hope to convey the awareness and perspective I wish to share with you, since change begins with awareness, and <strong>we have to change our way</strong> so that our children can live in the world they deserve! <img src="assets/images/waste.png" class="img-fluid quarto-figure quarto-figure-center" width="500" /></p>
<section id="are-we-aware" class="level1">
<h1><span style="color:darkgreen">1. Are we aware?</span> <img src="assets/images/trash.jpg" width="109" height="27" /></h1>
<p><strong><em>Important fact:</em></strong> Are we aware that when we do not recycle waste or use it for energy consumption, it pollutes our groundwater, our soil, and the air through greenhouse gases emitted by the waste, ultimately reducing the quality of the food produced in our soil and our overall life quality?</p>
<p>We just complain, don’t we? Strawberries used to smell like strawberries, tomatoes used to taste different… right?</p>
<p>Unfortunately, complaining doesn’t fix anything, and it won’t. If we want to deserve to live in this world, we must work hard for our generation. The effort we do not put into our waste will heavily come back to haunt us and our children in this universe created with karma. <strong>Let’s quit complaining and start acting!</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img src="assets/images/landfill-scaled.jpg" class="img-fluid quarto-figure quarto-figure-center" width="300" /></p>
</figure>
</div>
<p><strong><em>The scope:</em></strong> The processes and activities required to handle waste from its inception to its final disposal are called <strong><em>waste management.</em></strong> These activities include the collection, transport, treatment, and disposal of waste, as well as the monitoring and organization of waste management processes [1]. In this project, insights are attempted to be extracted from several data collections on waste management in Turkiye, with a particular focus on municipal waste statistics. Initially, data are analyzed on a national level, then the analysis is moved to a provincial basis. Then, time series methods are used to forecast waste amount trends in Turkiye. Additionally, the variables that influence the amounts of waste are investigated using regression analysis.</p>
<p><strong><em>The aim:</em></strong> In this project, the main goals are to increase awareness about waste issues, determine future waste quantities, investigate the waste levels of the provinces, and discuss both prevention strategies and proper disposal and recycling methods for unavoidable waste.</p>
<p><strong><em>Some information before the analysis:</em></strong> As of 2023, <strong><em>Turkiye’s population is 85 million 279 thousand 553 people</em></strong> and it has a total of 81 provinces, with Istanbul, Ankara, and Izmir being the most populous [2]. According to the data from 2022, <strong><em>1,389</em></strong> out of 1,391 municipalities in Turkiye <strong><em>provide waste management services</em></strong>, and it is amassed <strong><em>a total of 30,283,757 tons of waste</em></strong>, and the amount of MSW collected per person is <strong><em>1.03 kg/day</em></strong> [3]. From this total, <strong><em>85.9%</em></strong> was directed towards waste treatment facilities, <strong><em>13.5%</em></strong> was allocated to municipal dumping sites, and the remaining <strong><em>0.6%</em></strong> was disposed of through alternative methods such as open burning, burial, and the dumping into rivers or onto land [3].</p>
</section>
<section id="data" class="level1">
<h1><span style="color:darkgreen">2. Data</span> <img src="assets/images/data_symbol.jpg" width="43" height="29" /></h1>
<p><span style="color:darkred"><strong><em>Municipal Solid Waste (MSW)</em></strong></span>, waste collected by the municipalities that provide waste management services, includes everyday trash from homes, businesses, and public places, along with bulky items and yard waste. It also covers street sweepings and waste from public trash bins and markets, if treated like household trash. However, it doesn’t include waste from sewer systems, industrial processes or construction and demolition sites [4].</p>
<p>Multiple data sources are planned to be utilized for the analysis in this area of MSW, primarily focusing on waste quantities, along with Gross Domestic Product (GDP), education, electricity consumption, population figures, and agriculture area for <strong><em>Turkiye and its provinces.</em></strong></p>
<section id="data-source" class="level2">
<h2><span style="color:darkblue">2.1 Data Source</span> <img src="assets/images/database.jpg" width="71" height="29" /></h2>
<p>The references from which I have gathered the data include:</p>
<ul>
<li><a href="https://data.tuik.gov.tr/Bulten/Index?p=Waste-Statistics-2022-49570">Waste Statistics, TURKSTAT</a></li>
<li><a href="https://biruni.tuik.gov.tr/bolgeselistatistik/">Environment Regional Data, Biruni TURKSTAT</a></li>
<li><a href="https://biruni.tuik.gov.tr/bolgeselistatistik/">Agriculture area, Biruni TURKSTAT</a></li>
<li><a href="https://biruni.tuik.gov.tr/bolgeselistatistik/">Education, Biruni TURKSTAT</a></li>
<li><a href="https://biruni.tuik.gov.tr/bolgeselistatistik/">GDP, Biruni TURKSTAT</a></li>
<li><a href="https://biruni.tuik.gov.tr/bolgeselistatistik/">Electricity consumption, Biruni TURKSTAT</a></li>
</ul>
</section>
<section id="general-information-about-the-main-data" class="level2">
<h2><span style="color:darkblue">2.2 General Information About the Main Data</span> <img src="assets/images/info.jpg" width="26" height="23" /></h2>
<ul>
<li><strong>First data set:</strong> The municipal waste amount data of Turkiye, which includes information such as the population of Turkiye and its 81 provinces’ municipalities, total waste amounts for the year 2022, the average waste amount per person, etc.</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package &#39;openxlsx&#39; was built under R version 4.3.3</code></pre>
</div>
</div>
<ul>
<li><strong>Second data set:</strong> Data including the amounts of collected municipal waste that are sent to municipal landfills, waste processing facilities (the waste sent to landfill sites, incineration plants and all the waste recovery facilities), and disposed of using other methods (disposals by burning in an open area, dumping into river/onto land and burying).</li>
</ul>
<ul>
<li><strong>Third data set:</strong> Time series data including municipal waste amounts, waste per capita, waste sent to processing facilities, etc., and time series of waste amounts by provinces of Turkiye for the years 1994-2022.</li>
</ul>
</section>
<section id="reason-of-choice" class="level2">
<h2><span style="color:darkblue">2.3 Reason of Choice</span> <img src="assets/images/reason.jpg" width="25" height="21" /></h2>
<p>This topic was chosen because it was realized that <strong>waste management is not given enough importance</strong> in Turkiye, and it is believed that carelessness should not continue in this matter. The importance of the subject is <strong>indisputable</strong>. By using the data sets mentioned above, it is aimed to reveal and analyze the current situation of waste management, to derive knowledge, and to contribute to the literature and our country.</p>
</section>
<section id="preprocessing" class="level2">
<h2><span style="color:darkblue">2.4 Preprocessing</span> <img src="assets/images/preprocess.jpg" width="29" height="24" /></h2>
<ul>
<li><strong>For “municipal_waste” dataset:</strong></li>
</ul>
<p><a href="https://github.com/emu-hacettepe-analytics/emu660-spring2024-Dilara-pro/tree/main/project/data">Downloadable dataset in .RData version</a></p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package &#39;stringr&#39; was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                                        Provinces 
                                      &quot;character&quot; 
                       Total municipal population 
                                        &quot;numeric&quot; 
                   Total number of municipalities 
                                        &quot;numeric&quot; 
Number of municipalities providing waste services 
                                        &quot;numeric&quot; 
            Amount of waste collected (Tonnes) \n 
                                        &quot;numeric&quot; 
    Amount of waste per capita (Kg/capita-day) \n 
                                        &quot;numeric&quot; </code></pre>
</div>
</div>
<p>The first six rows of the municipal waste dataset are provided below.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>&#39;data.frame&#39;:   82 obs. of  6 variables:
 $ Provinces                                        : chr  &quot;Türkiye&quot; &quot;Adana&quot; &quot;Adıyaman&quot; &quot;Afyonkarahisar&quot; ...
 $ Total municipal population                       : num  80785141 2274106 487642 588048 314539 ...
 $ Total number of municipalities                   : num  1391 16 23 60 12 ...
 $ Number of municipalities providing waste services: num  1389 16 22 60 12 ...
 $ Amount of waste collected (Tonnes) 
            : num  30283757 665695 179724 198273 181116 ...
 $ Amount of waste per capita (Kg/capita-day) 
    : num  1.033 0.807 1.019 0.928 1.58 ...</code></pre>
</div>
</div>
<p>The descriptive statistics for each column are provided below.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  Provinces         Total municipal population Total number of municipalities
 Length:82          Min.   :   41120           Min.   :   4.00               
 Class :character   1st Qu.:  242100           1st Qu.:  11.00               
 Mode  :character   Median :  417945           Median :  16.00               
                    Mean   : 1970369           Mean   :  33.93               
                    3rd Qu.: 1139026           3rd Qu.:  21.00               
                    Max.   :80785141           Max.   :1391.00               
 Number of municipalities providing waste services
 Min.   :   4.00                                  
 1st Qu.:  11.00                                  
 Median :  16.00                                  
 Mean   :  33.88                                  
 3rd Qu.:  21.00                                  
 Max.   :1389.00                                  
 Amount of waste collected (Tonnes) \n
 Min.   :   21392                     
 1st Qu.:   81725                     
 Median :  151235                     
 Mean   :  738628                     
 3rd Qu.:  415882                     
 Max.   :30283757                     
 Amount of waste per capita (Kg/capita-day) \n
 Min.   :0.6498                               
 1st Qu.:0.8730                               
 Median :0.9672                               
 Mean   :1.0679                               
 3rd Qu.:1.1887                               
 Max.   :1.9962                               </code></pre>
</div>
</div>
<ul>
<li><strong>For “where_to_municipal_waste” dataset:</strong></li>
</ul>
<p><a href="https://github.com/emu-hacettepe-analytics/emu660-spring2024-Dilara-pro/tree/main/project/data">Downloadable dataset in .RData version</a></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                                Provinces 
                              &quot;character&quot; 
Total amount of waste collected  (Tonnes) 
                                &quot;numeric&quot; 
             Municipality&#39;s dumping sites 
                                &quot;numeric&quot; 
               Waste treatment facilities 
                                &quot;numeric&quot; 
                   Other disposal methods 
                                &quot;numeric&quot; </code></pre>
</div>
</div>
<p>The first six rows of the dataset showing the distribution of municipal waste disposal methods are provided below.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>&#39;data.frame&#39;:   82 obs. of  5 variables:
 $ Provinces                                : chr  &quot;Türkiye&quot; &quot;Adana&quot; &quot;Adıyaman&quot; &quot;Afyonkarahisar&quot; ...
 $ Total amount of waste collected  (Tonnes): num  30283757 665695 179724 198273 181116 ...
 $ Municipality&#39;s dumping sites             : num  4092721 0 178453 20090 131116 ...
 $ Waste treatment facilities               : num  26016988 663895 1271 175952 50000 ...
 $ Other disposal methods                   : num  174048 1800 0 2231 0 ...</code></pre>
</div>
</div>
<p>The descriptive statistics for each column are provided below.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  Provinces         Total amount of waste collected  (Tonnes)
 Length:82          Min.   :   21392                         
 Class :character   1st Qu.:   81725                         
 Mode  :character   Median :  151235                         
                    Mean   :  738628                         
                    3rd Qu.:  415882                         
                    Max.   :30283757                         
 Municipality&#39;s dumping sites Waste treatment facilities Other disposal methods
 Min.   :      0              Min.   :       0           Min.   :     0.0      
 1st Qu.:   1260              1st Qu.:   52770           1st Qu.:     0.0      
 Median :  17376              Median :  109595           Median :     0.0      
 Mean   :  99822              Mean   :  634561           Mean   :  4245.1      
 3rd Qu.:  56501              3rd Qu.:  333389           3rd Qu.:   557.5      
 Max.   :4092721              Max.   :26016988           Max.   :174047.6      </code></pre>
</div>
</div>
<ul>
<li><strong>For “time_series_municipal_waste” dataset and “ts_province” dataset:</strong></li>
</ul>
<p><a href="https://github.com/emu-hacettepe-analytics/emu660-spring2024-Dilara-pro/tree/main/project/data">Downloadable dataset in .RData version</a></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> Waste/Year        1994        1995        1996        1997        1998 
&quot;character&quot;   &quot;numeric&quot;   &quot;numeric&quot;   &quot;numeric&quot;   &quot;numeric&quot;   &quot;numeric&quot; 
       2001        2002        2003        2004        2006        2008 
  &quot;numeric&quot;   &quot;numeric&quot;   &quot;numeric&quot;   &quot;numeric&quot;   &quot;numeric&quot;   &quot;numeric&quot; 
       2010        2012        2014        2016        2018        2020 
  &quot;numeric&quot;   &quot;numeric&quot;   &quot;numeric&quot;   &quot;numeric&quot;   &quot;numeric&quot;   &quot;numeric&quot; 
       2022 
  &quot;numeric&quot; </code></pre>
</div>
</div>
<p>The attributes of the time series dataset are provided below.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>&#39;data.frame&#39;:   7 obs. of  19 variables:
 $ Waste/Year: chr  &quot;Turkey population&quot; &quot;Amount of municipal waste generated (Thousand tonnes/year)&quot; &quot;Amount of municipal waste collected (Thousand tonnes/year)&quot; &quot;Average amount of municipal waste per capita (Kg/capita-day)&quot; ...
 $ 1994      : num  6.28e+07 2.34e+04 1.78e+04 1.10 1.00e+03 ...
 $ 1995      : num  6.28e+07 2.72e+04 2.09e+04 1.27 1.60e+03 ...
 $ 1996      : num  6.28e+07 2.93e+04 2.25e+04 1.37 3.03e+03 ...
 $ 1997      : num  6.28e+07 3.19e+04 2.42e+04 1.46 4.54e+03 ...
 $ 1998      : num  6.28e+07 3.30e+04 2.49e+04 1.51 5.42e+03 ...
 $ 2001      : num  6.78e+07 3.10e+04 2.51e+04 1.35 8.52e+03 ...
 $ 2002      : num  6.78e+07 3.10e+04 2.54e+04 1.34 7.43e+03 ...
 $ 2003      : num  6.78e+07 3.11e+04 2.61e+04 1.38 7.76e+03 ...
 $ 2004      : num  6.78e+07 2.97e+04 2.50e+04 1.31 7.35e+03 ...
 $ 2006      : num  7.06e+07 3.01e+04 2.53e+04 1.21 9.68e+03 ...
 $ 2008      : num  7.06e+07 2.85e+04 2.44e+04 1.15 1.12e+04 ...
 $ 2010      : num  7.37e+07 2.97e+04 2.53e+04 1.14 1.39e+04 ...
 $ 2012      : num  7.56e+07 3.08e+04 2.58e+04 1.12 1.56e+04 ...
 $ 2014      : num  7.77e+07 3.12e+04 2.80e+04 1.08 1.79e+04 ...
 $ 2016      : num  7.98e+07 3.38e+04 3.16e+04 1.17 2.24e+04 ...
 $ 2018      : num  8.20e+07 3.45e+04 3.22e+04 1.16 2.56e+04 ...
 $ 2020      : num  8.36e+07 3.48e+04 3.23e+04 1.13 2.67e+04 ...
 $ 2022      : num  8.53e+07 3.24e+04 3.03e+04 1.03 2.60e+04 ...</code></pre>
</div>
</div>
<p>The attributes of the provinces’ time series dataset are provided below.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Zorlamadan dolayı ortaya çıkan NAs</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>&#39;data.frame&#39;:   1134 obs. of  3 variables:
 $ Year                   : num  1998 2001 2002 2003 2004 ...
 $ Province               : chr  &quot;İstanbul&quot; &quot;İstanbul&quot; &quot;İstanbul&quot; &quot;İstanbul&quot; ...
 $ Waste amount (1000 ton): num  6074 6112 5231 5375 4471 ...</code></pre>
</div>
</div>
</section>
</section>
<section id="analysis" class="level1">
<h1><span style="color:darkgreen">3. Analysis</span> <img src="assets/images/analysis.jpg" width="36" height="29" /></h1>
<p>In the first phase of this section, <em>Exploratory Data Analysis (EDA)</em>, the data prepared for analysis is visualized to enable discoveries that are not immediately apparent at first glance. Later, relationships are determined through <em>regression analysis</em>, future predictions are made using <em>time series methods</em>.</p>
<section id="exploratory-data-analysis" class="level2">
<h2><span style="color:darkblue">3.1 Exploratory Data Analysis</span> <img src="assets/images/EDA.jpg" width="23" height="21" /></h2>
<p><span style="color:purple"><strong>For “municipal_waste” dataset:</strong></span></p>
<p>The relationship between the population size of Turkiye provinces and the amount of waste generated is shown in the scatter plot below. According to the plot, a linear relationship is observed between them.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package &#39;ggthemes&#39; was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package &#39;ggrepel&#39; was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure>
<p><img src="project_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672" /></p>
</figure>
</div>
</div>
</div>
<p>Provinces ranked according to the total number of municipalities can be seen in the below graph together with the number of municipalities.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img src="project_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672" /></p>
</figure>
</div>
</div>
</div>
<p>In the plot below, the first 20 provinces with the highest amount of waste per capita and their populations can be found.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img src="project_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672" /></p>
</figure>
</div>
</div>
</div>
<p><span style="color:purple"><strong>For “where_to_municipal_waste” dataset:</strong></span></p>
<p>The distribution of waste collected by municipalities according to three disposal methods and provinces is analysed in this section.</p>
<p>The amount of waste allocated for the <em>municipality dumping site</em> can be seen below, plotted by province, with circle diameters representing the total amount of waste.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img src="project_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672" /></p>
</figure>
</div>
</div>
</div>
<p>The amount of waste allocated for the <em>waste treatment facilities</em> can be seen below, plotted by province, with circle diameters representing the total amount of waste.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img src="project_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672" /></p>
</figure>
</div>
</div>
</div>
<p>The amount of waste allocated for the <em>other disposal methods</em> can be seen below, plotted by province, with circle diameters representing the total amount of waste.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img src="project_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672" /></p>
</figure>
</div>
</div>
</div>
<p>The pie chart below shows a rough breakdown of the amount of waste sent to these three disposal methods.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img src="project_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672" /></p>
</figure>
</div>
</div>
</div>
<p><span style="color:purple"><strong>For “time_series_municipal_waste” dataset and “ts_province” dataset:</strong></span></p>
<p>According to the time series data set, Turkiye’s population change over the years is given below.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img src="project_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672" /></p>
</figure>
</div>
</div>
</div>
<p>The relationship between the total amount of waste generated in Turkiye and the amount collected by municipalities for proper disposal can be accessed from the plot.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img src="project_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672" /></p>
</figure>
</div>
</div>
</div>
<p>Changes in waste amount over the years according to disposal methods are given below.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img src="project_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672" /></p>
</figure>
</div>
</div>
</div>
<p>Descriptive statistics for waste amounts by province dataset:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 6
   Province mean_waste median_waste sd_waste min_waste max_waste
   &lt;chr&gt;         &lt;dbl&gt;        &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
 1 İstanbul      5879.        5898     824.       4471      7043
 2 Ankara        2182.        2204.    158.       1881      2363
 3 İzmir         1654.        1538.    336.       1329      2337
 4 Antalya        948.         872.    239.        666      1341
 5 Bursa          879          854.    203.        618      1181
 6 Konya          756.         740.     84.7       643       921
 7 Adana          731.         734      63.6       614       826
 8 Mersin         613.         595      97.8       453       819
 9 Kocaeli        539.         534     110.        380       713
10 Muğla          529.         528.     99.9       397       677</code></pre>
</div>
</div>
<p>The line graph of waste amounts over the years for the top 5 cities producing the most waste based on provincial waste amount data is drawn.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img src="project_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672" /></p>
</figure>
</div>
</div>
</div>
<p>The box plot for the top 10 provinces with the highest average waste amounts is provided below.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img src="project_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672" /></p>
</figure>
</div>
</div>
</div>
<p>When İstanbul, which was very dominant in the previous boxplot, is excluded, the results are also examined.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img src="project_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672" /></p>
</figure>
</div>
</div>
</div>
</section>
<section id="regression-analysis" class="level2">
<h2><span style="color:darkblue">3.2 Regression Analysis</span> <img src="assets/images/tredn.jpg" width="26" height="23" /></h2>
<p><strong><em>Additional Data</em></strong></p>
<p>The data sets needed to identify variables contributing to total waste generation and to conduct regression analysis have been preprocessed below.</p>
<p>Data on the <span style="color:red">agricultural area</span> cultivated in the provinces of Turkiye can be accessed below.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>&#39;data.frame&#39;:   81 obs. of  2 variables:
 $ Provinces       : chr  &quot;İstanbul&quot; &quot;Tekirdağ&quot; &quot;Edirne&quot; &quot;Kırklareli&quot; ...
 $ Agriculture area: num  74041 403706 335499 245224 288589 ...</code></pre>
</div>
</div>
<p>The data on <span style="color:red">educational status</span> of Turkiye’s provinces, categorized by various levels, is provided in education data set.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>&#39;data.frame&#39;:   81 obs. of  5 variables:
 $ Provinces                                         : chr  &quot;İstanbul&quot; &quot;Tekirdağ&quot; &quot;Edirne&quot; &quot;Kırklareli&quot; ...
 $ Total number of faculty members                   : num  40140 1221 1871 883 1837 ...
 $ Total number of illiterate people                 : num  206140 11573 7011 4462 17368 ...
 $ Number of associate or bachelor&#39;s degree graduates: num  167695 3728 6517 3682 7465 ...
 $ Number of master&#39;s degree graduates               : num  389440 14458 6914 5137 18318 ...</code></pre>
</div>
</div>
<p>The first six rows of the <span style="color:red">electricity consumption</span> data for the provinces of Turkiye are as follows.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>&#39;data.frame&#39;:   81 obs. of  3 variables:
 $ Provinces                               : chr  &quot;İstanbul&quot; &quot;Tekirdağ&quot; &quot;Edirne&quot; &quot;Kırklareli&quot; ...
 $ Total electricity consumption (MWh)     : num  41520357 8502879 1299120 2715585 4276586 ...
 $ Electricity consumption per capita (KWh): num  2621 7637 3152 7412 3420 ...</code></pre>
</div>
</div>
<p><span style="color:red">The GDP</span> data for the provinces of Turkiye has been obtained.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>&#39;data.frame&#39;:   82 obs. of  3 variables:
 $ Provinces          : chr  &quot;Türkiye&quot; &quot;İstanbul&quot; &quot;Tekirdağ&quot; &quot;Edirne&quot; ...
 $ GDP per capita (TL): num  176651 287524 253501 147752 201355 ...
 $ GDP per capita ($) : num  10659 17349 15296 8915 12150 ...</code></pre>
</div>
</div>
<p>If the <span style="color:red">response variable</span> is extracted from the municipal data set, the desired variable of <span style="color:red">waste amount</span> by province can be obtained for the analysis.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>&#39;data.frame&#39;:   81 obs. of  2 variables:
 $ Provinces                         : chr  &quot;Adana&quot; &quot;Adıyaman&quot; &quot;Afyonkarahisar&quot; &quot;Ağrı&quot; ...
 $ Amount of waste collected (Tonnes): num  665695 179724 198273 181116 111099 ...</code></pre>
</div>
</div>
<p><span style="color:red">The regression analysis</span> below has been conducted using the <span style="color:red">total amount of waste collected</span> at the provincial level as the response variable. <span style="color:red">The independent variables</span> include <span style="color:red">GDP per capita, agricultural area, total number of faculty members, total number of illiterate people, number of associate or bachelor’s degree graduates, number of master’s degree graduates, and electricity consumption</span>. The final table prepared for regression analysis can be found below.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>&#39;data.frame&#39;:   82 obs. of  11 variables:
 $ Provinces                                         : chr  &quot;Adana&quot; &quot;Adıyaman&quot; &quot;Afyonkarahisar&quot; &quot;Ağrı&quot; ...
 $ Amount of waste collected (Tonnes)                : num  665695 179724 198273 181116 111099 ...
 $ Agriculture area                                  : num  400819 166921 536127 351566 235758 ...
 $ Total number of faculty members                   : num  2593 925 1647 561 725 ...
 $ Total number of illiterate people                 : num  54962 26688 12334 25954 6815 ...
 $ Number of associate or bachelor&#39;s degree graduates: num  7987 2453 6787 2065 2870 ...
 $ Number of master&#39;s degree graduates               : num  33810 7359 9331 3925 4385 ...
 $ Total electricity consumption (MWh)               : num  7991581 1327087 2131943 495005 706136 ...
 $ Electricity consumption per capita (KWh)          : num  3531 2099 2865 944 2106 ...
 $ GDP per capita (TL)                               : num  135798 79223 114168 55296 112044 ...
 $ GDP per capita ($)                                : num  8194 4780 6889 3337 6761 ...</code></pre>
</div>
</div>
<p><strong><em>Regression Analysis</em></strong></p>
<p>In regression analysis using the forward selection method, the model begins with the variable that exhibits the highest correlation with the response variable, ‘Amount of waste collected’. Subsequently, additional variables are incorporated into the model based on their partial correlations.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package &#39;ppcor&#39; was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Zorunlu paket yükleniyor: MASS</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: &#39;MASS&#39;</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from &#39;package:dplyr&#39;:

    select</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package &#39;readxl&#39; was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                        [,1]
Agriculture area                                   0.1237475
Total number of faculty members                    0.9500715
Total number of illiterate people                  0.8469772
Number of associate or bachelor&#39;s degree graduates 0.7395918
Number of master&#39;s degree graduates                0.9708360
Total electricity consumption (MWh)                0.9327005
GDP per capita (TL)                                0.5047206</code></pre>
</div>
</div>
<p>The plot between the response variable and the independent variable with <span style="color:red">highest correlation (Number of master’s degree graduates)</span>:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img src="project_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672" /></p>
</figure>
</div>
</div>
</div>
<p><span style="color:red">Partial correlations</span>: between variables while controlling the variable with the highest correlation:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   estimate      p.value statistic  n gp  Method
1 0.5732279 2.742934e-08  6.178469 81  1 pearson</code></pre>
</div>
</div>
<p>When examining the partial correlation values for other columns, taking into account those with significant p-values, <span style="color:red">the variable with the highest partial correlation is ‘Total electricity consumption’</span>. Therefore, it should be the second variable added to the regression model.</p>
<p>In the next step, partial correlations are examined while controlling for the two variables with the highest correlations this time. Those that pass the significant test from the previous step are included in this calculations.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  estimate     p.value statistic  n gp  Method
1 0.334597 0.002578755  3.115659 81  2 pearson</code></pre>
</div>
</div>
<p>When the partial correlations calculated by controlling for the two variables were checked, both were less than 0.5. In other words, there are no remaining variables with a strong relationship. <strong><em>In the final model, the independent variables affecting the response variable “Amount of waste collected” were selected as “Number of master’s degree graduates” and “Total electricity consumption” using the forward selection method.</em></strong></p>
<p>The results of the multiple regression analysis with the relevant columns are as follows.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = `Amount of waste collected (Tonnes)` ~ `Number of master&#39;s degree graduates` + 
    `Total electricity consumption (MWh)`, data = ln_version_reg_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.29626 -0.09862 -0.00168  0.07417  0.31978 

Coefficients:
                                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                            1.26657    0.18717   6.767 2.18e-09 ***
`Number of master&#39;s degree graduates`  0.87283    0.07469  11.687  &lt; 2e-16 ***
`Total electricity consumption (MWh)`  0.09492    0.06526   1.455     0.15    
---
Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1

Residual standard error: 0.13 on 78 degrees of freedom
Multiple R-squared:  0.9254,    Adjusted R-squared:  0.9234 
F-statistic: 483.4 on 2 and 78 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><span style="color:red">Since the variable representing total electricity consumption is not significant, it has been excluded from the model.</span> Therefore, the most suitable and effective version of our model, achieving the highest possible R-squared value, is the simple regression model that solely includes the variable “Number of master’s graduates”.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = `Amount of waste collected (Tonnes)` ~ `Number of master&#39;s degree graduates`, 
    data = ln_version_reg_data)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.312666 -0.083161 -0.001103  0.064059  0.303947 

Coefficients:
                                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                             1.4720     0.1237   11.90   &lt;2e-16 ***
`Number of master&#39;s degree graduates`   0.9715     0.0315   30.84   &lt;2e-16 ***
---
Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1

Residual standard error: 0.1309 on 79 degrees of freedom
Multiple R-squared:  0.9233,    Adjusted R-squared:  0.9224 
F-statistic: 951.3 on 1 and 79 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term                                  estimate std.error statistic  p.value
  &lt;chr&gt;                                    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)                              1.47     0.124       11.9 2.68e-19
2 `Number of master&#39;s degree graduates`    0.971    0.0315      30.8 8.17e-46</code></pre>
</div>
</div>
<p><span style="color:red"><strong><em>Model adequacy checking</em></strong></span> in a regression model is best achieved by thoroughly analyzing the residuals. Below are the graphs related to <span style="color:red">residual analysis.</span></p>
<p>There seems no problem in Residual vs Fitted values plot. This means that <strong><em>the assumption of constant variance is satisfied.</em></strong></p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure>
<p><img src="project_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672" /></p>
</figure>
</div>
</div>
</div>
<p>The q-q plot to check if residuals are normally distributed is drawn, and there is no problem with that.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img src="project_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672" /></p>
</figure>
</div>
</div>
</div>
<p>In the Q-Q plot, tails are observed on both the right and left sides. To be sure, an Anderson-Darling normality test should also be conducted.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Anderson-Darling normality test

data:  residuals
A = 0.43796, p-value = 0.2882</code></pre>
</div>
</div>
<p>A p-value of 0.28 in the Anderson-Darling test indicates that there is not enough evidence to reject the null hypothesis that the residuals are normally distributed. Therefore, it can be assumed that the residuals are normally distributed; <strong><em>the normality assumption for the regression model’s residuals is considered to be met.</em></strong></p>
<p>The plot below helps to check for <strong><em>homoscedasticity</em></strong>. According to it, <strong><em>there is no such a problem.</em></strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img src="project_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="672" /></p>
</figure>
</div>
</div>
</div>
</section>
<section id="time-series-analysis" class="level2">
<h2><span style="color:darkblue">3.3 Time Series Analysis</span> <img src="assets/images/model.jpg" width="36" height="28" /></h2>
<p>The MSW time series data for Turkiye lacks values for some intermediate years (e.g. 2017, 2019, 2021, etc.), which implies that time series analysis must be conducted under incomplete information. In this respect, <strong>Grey Prediction (GP)</strong> is a powerful forecasting approach to effectively manage the forecast analysis for MSW [6]. This method is particularly advantageous when data availability is limited, as it requires only a few data points to construct reliable models [6]. The core idea of GP involves transforming a complex data series into a more predictable one using a set of operations, such as the Accumulated Generating Operator (AGO), the Inverse Accumulating Operator (IAGO) and Grey Model (GM) [6].</p>
<p>The ExoplanetX greyforecasting R package is used to apply GP models to the MSW time series [7]. All GP models included in the package are applied to the data in the background, and the best model in terms of performance is provided along with its accuracy and 5-year forecasting results.</p>
<p>The GP models in the package are as follows (*):</p>
<ol type="1">
<li><p><strong>gm:</strong> Grey Model (1,1), It’s a first-order differential equation model with one variable.</p></li>
<li><p><strong>gm_1:</strong> GM(1,1)_1, This variant of the GM(1,1) model includes slight modifications or improvements over the standard GM(1,1) model to enhance prediction accuracy or adapt to specific types of data.</p></li>
<li><p><strong>gm_2:</strong> GM(1,1)_2, Another variant of the GM(1,1) model, with different modifications from GM(1,1)_1, aiming to improve forecasting performance under certain conditions.</p></li>
<li><p><strong>dgm:</strong> Discrete Grey Model, This model is a discrete version of the grey prediction model, which operates on discrete data points rather than continuous data, making it suitable for time series data that are naturally discrete.</p></li>
<li><p><strong>verhulst:</strong> Verhulst Model, The Verhulst model is a nonlinear grey prediction model that is particularly useful for data that follow an S-shaped growth curve, such as population growth or diffusion processes.</p></li>
<li><p><strong>pgm:</strong> Grey Power Model, The Grey Power Model is another variant of grey models that incorporates power functions into the grey modeling process to handle data with certain types of nonlinearity.</p></li>
</ol>
<p>First, the necessary packages are installed, and libraries are called.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: &#39;greyforecasting&#39;</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from &#39;package:dplyr&#39;:

    combine</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package &#39;Metrics&#39; was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: &#39;Metrics&#39;</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from &#39;package:greyforecasting&#39;:

    ape, mape</code></pre>
</div>
</div>
<p>When all models are applied to the data in the background, the method that gives the best result is the <strong>DGM (Discrete Grey Model)</strong> method.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>The best model is: dgm </code></pre>
</div>
</div>
<p>Then, the accuracy metric value and forecast values for the next 5 years are provided for the DGM model.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Best model RMSE: 1365.859 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 30271.09 30922.96 30883.69 31518.20 31456.93</code></pre>
</div>
</div>
<p>Finally, the original data, fitted values, and forecast points are shown in the graph below.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img src="project_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid" width="672" /></p>
</figure>
</div>
</div>
</div>
<p>In the above graph, an increasing trend over the years is observed due to the consideration of total waste amounts. However, Turkiye’s population growth is also a factor that must be taken into account. When analyzing the per capita waste production instead of the total amounts, the graph below is obtained.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>The best model is: dgm </code></pre>
</div>
</div>
<p>Then, the accuracy metric value and forecast values for the next 5 years are provided for the DGM model.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Best model RMSE: 0.1330711 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9997255 1.0134248 0.9806750 0.9938774 0.9619003</code></pre>
</div>
</div>
<p>Finally, the original data, fitted values, and forecast points are shown in the graph below.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img src="project_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid" width="672" /></p>
</figure>
</div>
</div>
</div>
<p>In the waste per capita case, the best fit model according to RMSE is again the DGM. Unlike before, a decreasing trend over the years is noticeable in above figure, indicating that the increasing population must be considered in the analysis.</p>
<p>The following are the results obtained when performing the same grey forecasting analysis for Ankara.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>The best model is: dgm </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Best model RMSE: 290.0232 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1884.965 1933.066 1861.282 1907.419 1836.855</code></pre>
</div>
</div>
<p>The graph:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img src="project_files/figure-html/unnamed-chunk-53-1.png" class="img-fluid" width="672" /></p>
</figure>
</div>
</div>
</div>
<p>Based on the time series analysis, it was concluded that the DGM model is the most appropriate time series model for the data containing total MSW quantities. The fact that data is not available at irregular intervals of time already tells us that the model suitable for the data should be discrete. The DGM model forecasted the next five years with the following values: 30,271.09, 30,922.96, 30,883.69, 31,518.20, and 31,456.93 tonnes. As shown in plots above, the model closely fits the historical data and strengthens the reliability of these forecast values. It is also the best method according to the RMSE performance metric.</p>
<p>The observed increasing trend is consistent with Turkiye’s historical waste generation patterns and highlights the increasing waste management challenge posed by urbanization and population growth. In addition, considering Turkiye’s population growth, waste generation per capita was also analysed in the study. The per capita waste forecasts have shown a decreasing trend over the years.</p>
<p>In addition, the MSW time series analysis of our city (Ankara) is also included. The DGM model was again dominant, which is logical since it is again an interval time data.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1><span style="color:darkgreen">4. Conclusion</span> <img src="assets/images/discussion.png" class="img-fluid" width="27" /></h1>
<p>Effective planning of solid waste management systems depends on analysing and forecasting MSW flows. Accordingly, analysing waste quantity data is crucial for informed decision-making and strategic planning related to waste management in Turkiye. In this respect, the aim of this study is to analyse and forecast MSW quantities in Turkiye by examining socio-economic factors through regression analysis and applying time series models for forecasting.</p>
<p>Firstly, EDA was applied to the dataset to reveal the underlying relationships and patterns in the data. Factors (economic, education, agriculture, electricity, etc.) that are thought to affect the amount of waste are added as data and a regression analysis is performed. As a result, a model using the number of master’s degree graduates in relation to the amount of waste was established and proved to be accurate.</p>
<p>Then, time series models were evaluated to predict future MSW quantities. Since the structure of the dataset is discrete with no regular values in intermediate periods, it was decided that GP methods are appropriate. Among the GP models, the DGM model was found to be the most appropriate model for the given data due to its discrete nature and high accuracy, as indicated by the RMSE performance measure. The observed upward trend in waste generation is in line with Turkiye’s historical data and emphasizes the increasing challenge of waste management in urban areas.</p>
<p>Strategic decision-making in waste management systems are crucial to overcome these challenges. The findings underline the necessity of sustainable waste management practices and sound policies to reduce the environmental impacts of increasing waste generation.</p>
</section>
<section id="references" class="level1">
<h1><span style="color:darkgreen">References</span> <img src="assets/images/references.jpg" width="30" height="29" /></h1>
<ol type="1">
<li>A. E. İnce, “Defining New Political Tools for Municipal Solid Waste Management of Ankara Metropolitan Municipalitiy After Revision of Metropolitan Municipality Law in 2014,” Master’s Thesis, Middle East Technical University, Council of Higher Education Thesis Center, 2019.</li>
<li>TURKSTAT. “The Results of Address Based Population Registration System, 2023.” https://data.tuik.gov.tr/Bulten/Index?p=The-Results-of-Address-Based-Population-Registration-System-2023-49684&amp;dil=2 (accessed May 5, 2024).</li>
<li>TURKSTAT. “Waste Statistics, 2022.” https://data.tuik.gov.tr/Bulten/Index?p=Waste-Statistics-2022-49570&amp;dil=2 (accessed May 3, 2024).</li>
<li>OECD. “Municipal Waste.” https://data.oecd.org/waste/municipal-waste.htm (accessed April 21, 2024).</li>
<li>H.-W. Chen and N.-B. Chang, “Prediction analysis of solid waste generation based on grey fuzzy dynamic modeling,” Resources, conservation and Recycling, vol. 29, no. 1-2, pp. 1-18, 2000.</li>
<li>D. Akay and M. Atak, “Grey prediction with rolling mechanism for electricity demand forecasting of Turkey,” energy, vol. 32, no. 9, pp. 1670-1675, 2007.</li>
<li>ExoplanetX. “Greyforecasting: A package for grey systems forecasting methods.” https://rdrr.io/github/exoplanetX/greyforecasting/. (accessed May 15, 2024).</li>
</ol>
<p>(*) ChatGPT</p>
<div id="quarto-navigation-envelope" class="hidden">
<p><span class="hidden" data-render-id="quarto-int-sidebar-title">Dilara’s Analytics Lab</span> <span class="hidden" data-render-id="quarto-int-navbar-title">Dilara’s Analytics Lab</span> <span class="hidden" data-render-id="quarto-int-navbar:Home">Home</span> <span class="hidden" data-render-id="quarto-int-navbar:/index.html">/index.html</span> <span class="hidden" data-render-id="quarto-int-navbar:About Me">About Me</span> <span class="hidden" data-render-id="quarto-int-navbar:/about.html">/about.html</span> <span class="hidden" data-render-id="quarto-int-navbar:My Posts">My Posts</span> <span class="hidden" data-render-id="quarto-int-navbar:/posts.html">/posts.html</span> <span class="hidden" data-render-id="quarto-int-navbar:EMU660 Coursework">EMU660 Coursework</span> <span class="hidden" data-render-id="quarto-int-navbar:Assignments">Assignments</span> <span class="hidden" data-render-id="quarto-int-navbar:/assignments.html">/assignments.html</span> <span class="hidden" data-render-id="quarto-int-navbar:Project">Project</span> <span class="hidden" data-render-id="quarto-int-navbar:/project.html">/project.html</span> <span class="hidden" data-render-id="quarto-navbar-tools:https://github.com/Dilara-pro">https://github.com/Dilara-pro</span> <span class="hidden" data-render-id="quarto-navbar-tools:https://www.linkedin.com/in/dilara-akkus/">https://www.linkedin.com/in/dilara-akkus/</span></p>
<div class="hidden" data-render-id="footer-center">
<p>Hacettepe IE - EMU660 - Spring 2024</p>
</div>
</div>
<div id="quarto-meta-markdown" class="hidden">
<p><span class="hidden" data-render-id="quarto-metatitle">Dilara’s Analytics Lab - STOP COMPLAINING, IT SOLVES NOTHING.</span> <span class="hidden" data-render-id="quarto-twittercardtitle">Dilara’s Analytics Lab - STOP COMPLAINING, IT SOLVES NOTHING.</span> <span class="hidden" data-render-id="quarto-ogcardtitle">Dilara’s Analytics Lab - STOP COMPLAINING, IT SOLVES NOTHING.</span> <span class="hidden" data-render-id="quarto-metasitename">Dilara’s Analytics Lab</span> <span class="hidden" data-render-id="quarto-twittercarddesc"></span> <span class="hidden" data-render-id="quarto-ogcardddesc"></span></p>
</div>
</section>

</main> <!-- /main -->
<script id = "quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      <div class='footer-contents'>Hacettepe IE - EMU660 - Spring 2024</div>  
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>

</body>

</html>
